### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by karen-pal** [dogecodes/react-chat#2]
Sorry for the noob question, I found this repo and the project seems awesome!! but after installing it, and running it, it shows a login page... do i need an account to use it? I tried signing up and it says `NetworkError when attempting to fetch resource.`

is there a mock i have to use? or how do i go at it?

**Comment by denysdovhan** [comment]
You need to start both API and client. You can find API repo here: https://github.com/dogecodes/react-chat-api

Just clone and run `npm start` in both repos.
